#!/bin/bash
cd ~/work
wget https://raw.githubusercontent.com/306bobby-android/crDroid-build-signed-script/main/create-signed-env.sh
chmod +x create-signed-env.sh
./create-signed-env.sh
source build/envsetup.sh
lunch lineage_RMX1901-user
m evolution
