#!/bin/bash
cd ~/work

# Signing
curl -O wget https://raw.githubusercontent.com/Shravan55555/crDroid-build-signed-script/main/create-signed-env.sh
chmod +x create-signed-env.sh
./create-signed-env.sh
source build/envsetup.sh
lunch derp_RMX1901-user
mka derp && wget https://gitlab.com/GustavoMends/go-up/-/raw/master/go-up && chmod +x go-up && ./go-up
