#!/bin/bash
. build/envsetup.sh
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 60G
ccache -o compression=true
ccache -z
lunch "$LUNCH_COMBO"
$EXTRA_CMD
mka $TARGET -j8
