#!/bin/bash
chk() {
df -h
free -h
nproc
cat /etc/os*
env
}
sudo apt update &&sudo apt install pigz wget
sudo apt install jq -y
c_down() {
cd /tmp
time aria2c $URI -x16 -s50
time tar xf ccache1.tar.gz
}

echo "Checking free space"
chk
echo "Downloading ccache"
c_down
echo "Done"
