#!/bin/bash
sync() {
mkdir -p ~/work
cd ~/work
git config --global user.name "Shravan55555"
git config --global user.email "srasidda.ks@gmail.com"
repo init --depth=1 -u $MANIFEST
git clone $LOCAL_MANIFEST .repo/local_manifests
repo sync --current-branch --no-tags -j4
}

echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
